name: funclust
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - flask=3.1.0

  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - openpyxl=3.1.5
  - pandas=2.2.3
  - plotly=5.24.1
  - pyarrow=19.0.0
  - scikit-bio=0.6.3
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - sklearn-compat=0.1.3
  - sympy=1.13.3
  - pip
  - pip:
      - polars==1.26.0
      - xlsxwriter==3.2.3
      - kaleido
